//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(Tenant.Models.TenantDbContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsf717395d0eb67b6547786b41d673e0211b12025a6919a99cdb95e1a42502821e))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework 6 Power Tools", "0.9.2.0")]
    internal sealed class ViewsForBaseEntitySetsf717395d0eb67b6547786b41d673e0211b12025a6919a99cdb95e1a42502821e : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "f717395d0eb67b6547786b41d673e0211b12025a6919a99cdb95e1a42502821e"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.WebApiUsage")
            {
                return GetView0();
            }

            if (extentName == "TenantDbContext.ApiLog")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.Application")
            {
                return GetView2();
            }

            if (extentName == "CodeFirstDatabase.TenantMaster")
            {
                return GetView3();
            }

            if (extentName == "CodeFirstDatabase.DatabaseBackupLog")
            {
                return GetView4();
            }

            if (extentName == "CodeFirstDatabase.IntegrationEventMaster")
            {
                return GetView5();
            }

            if (extentName == "CodeFirstDatabase.Subscriber")
            {
                return GetView6();
            }

            if (extentName == "CodeFirstDatabase.JobTrack")
            {
                return GetView7();
            }

            if (extentName == "CodeFirstDatabase.TenantMasterApplication")
            {
                return GetView8();
            }

            if (extentName == "CodeFirstDatabase.SubscriberIntegrationEventMaster")
            {
                return GetView9();
            }

            if (extentName == "TenantDbContext.Applications")
            {
                return GetView10();
            }

            if (extentName == "TenantDbContext.Tenants")
            {
                return GetView11();
            }

            if (extentName == "TenantDbContext.BackupLogs")
            {
                return GetView12();
            }

            if (extentName == "TenantDbContext.IntegrationEvents")
            {
                return GetView13();
            }

            if (extentName == "TenantDbContext.Integrations")
            {
                return GetView14();
            }

            if (extentName == "TenantDbContext.Jobs")
            {
                return GetView15();
            }

            if (extentName == "TenantDbContext.TenantMaster_Applications")
            {
                return GetView16();
            }

            if (extentName == "TenantDbContext.Subscriber_Events")
            {
                return GetView17();
            }

            if (extentName == "CodeFirstDatabase.FuelCompany")
            {
                return GetView18();
            }

            if (extentName == "CodeFirstDatabase.IOCPump")
            {
                return GetView19();
            }

            if (extentName == "CodeFirstDatabase.RateLog")
            {
                return GetView20();
            }

            if (extentName == "CodeFirstDatabase.HPCLTown")
            {
                return GetView21();
            }

            if (extentName == "CodeFirstDatabase.StateMaster")
            {
                return GetView22();
            }

            if (extentName == "TenantDbContext.FuelCompanies")
            {
                return GetView23();
            }

            if (extentName == "TenantDbContext.Pumps")
            {
                return GetView24();
            }

            if (extentName == "TenantDbContext.RateLogs")
            {
                return GetView25();
            }

            if (extentName == "TenantDbContext.Towns")
            {
                return GetView26();
            }

            if (extentName == "TenantDbContext.States")
            {
                return GetView27();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.WebApiUsage.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing WebApiUsage
        [CodeFirstDatabaseSchema.WebApiUsage](T1.WebApiUsage_Id, T1.WebApiUsage_TenantKey, T1.WebApiUsage_ApplicationKey, T1.WebApiUsage_UserKey, T1.WebApiUsage_RequestTimestamp, T1.WebApiUsage_ResponseTimestamp, T1.WebApiUsage_RequestContent, T1.WebApiUsage_ResponseContent, T1.WebApiUsage_RequestHeaders, T1.WebApiUsage_ResponseHeaders, T1.WebApiUsage_Uri, T1.WebApiUsage_RequestMethod, T1.WebApiUsage_IP, T1.WebApiUsage_ResponseStatusCode)
    FROM (
        SELECT 
            T.Id AS WebApiUsage_Id, 
            T.TenantKey AS WebApiUsage_TenantKey, 
            T.ApplicationKey AS WebApiUsage_ApplicationKey, 
            T.UserKey AS WebApiUsage_UserKey, 
            T.RequestTimestamp AS WebApiUsage_RequestTimestamp, 
            T.ResponseTimestamp AS WebApiUsage_ResponseTimestamp, 
            T.RequestContent AS WebApiUsage_RequestContent, 
            T.ResponseContent AS WebApiUsage_ResponseContent, 
            T.RequestHeaders AS WebApiUsage_RequestHeaders, 
            T.ResponseHeaders AS WebApiUsage_ResponseHeaders, 
            T.Uri AS WebApiUsage_Uri, 
            T.RequestMethod AS WebApiUsage_RequestMethod, 
            T.IP AS WebApiUsage_IP, 
            T.ResponseStatusCode AS WebApiUsage_ResponseStatusCode, 
            True AS _from0
        FROM TenantDbContext.ApiLog AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.ApiLog.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing ApiLog
        [Tenant.Models.WebApiUsage](T1.WebApiUsage_Id, T1.WebApiUsage_TenantKey, T1.WebApiUsage_ApplicationKey, T1.WebApiUsage_UserKey, T1.WebApiUsage_RequestTimestamp, T1.WebApiUsage_ResponseTimestamp, T1.WebApiUsage_RequestContent, T1.WebApiUsage_ResponseContent, T1.WebApiUsage_RequestHeaders, T1.WebApiUsage_ResponseHeaders, T1.WebApiUsage_Uri, T1.WebApiUsage_RequestMethod, T1.WebApiUsage_IP, T1.WebApiUsage_ResponseStatusCode)
    FROM (
        SELECT 
            T.Id AS WebApiUsage_Id, 
            T.TenantKey AS WebApiUsage_TenantKey, 
            T.ApplicationKey AS WebApiUsage_ApplicationKey, 
            T.UserKey AS WebApiUsage_UserKey, 
            T.RequestTimestamp AS WebApiUsage_RequestTimestamp, 
            T.ResponseTimestamp AS WebApiUsage_ResponseTimestamp, 
            T.RequestContent AS WebApiUsage_RequestContent, 
            T.ResponseContent AS WebApiUsage_ResponseContent, 
            T.RequestHeaders AS WebApiUsage_RequestHeaders, 
            T.ResponseHeaders AS WebApiUsage_ResponseHeaders, 
            T.Uri AS WebApiUsage_Uri, 
            T.RequestMethod AS WebApiUsage_RequestMethod, 
            T.IP AS WebApiUsage_IP, 
            T.ResponseStatusCode AS WebApiUsage_ResponseStatusCode, 
            True AS _from0
        FROM CodeFirstDatabase.WebApiUsage AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Application.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Application
        [CodeFirstDatabaseSchema.Application](T1.Application_Id, T1.Application_ApplicationName, T1.Application_ApplicationType, T1.Application_IsActive)
    FROM (
        SELECT 
            T.Id AS Application_Id, 
            T.ApplicationName AS Application_ApplicationName, 
            CAST(T.ApplicationType AS [Edm.Int32]) AS Application_ApplicationType, 
            T.IsActive AS Application_IsActive, 
            True AS _from0
        FROM TenantDbContext.Applications AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.TenantMaster.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TenantMaster
        [CodeFirstDatabaseSchema.TenantMaster](T1.TenantMaster_Id, T1.TenantMaster_Name, T1.TenantMaster_ClientKey, T1.TenantMaster_Secret, T1.TenantMaster_IsActive, T1.TenantMaster_ConnectionString, T1.TenantMaster_PostalAddress, T1.TenantMaster_PANNo, T1.TenantMaster_PhoneNumber, T1.TenantMaster_EmailAddress, T1.TenantMaster_WebAddress, T1.TenantMaster_LogType, T1.TenantMaster_ServerUrl, T1.TenantMaster_RemoteBackupPath, T1.TenantMaster_IsSingleUserMode, T1.TenantMaster_AccessCode)
    FROM (
        SELECT 
            T.Id AS TenantMaster_Id, 
            T.Name AS TenantMaster_Name, 
            T.ClientKey AS TenantMaster_ClientKey, 
            T.Secret AS TenantMaster_Secret, 
            T.IsActive AS TenantMaster_IsActive, 
            T.ConnectionString AS TenantMaster_ConnectionString, 
            T.PostalAddress AS TenantMaster_PostalAddress, 
            T.PANNo AS TenantMaster_PANNo, 
            T.PhoneNumber AS TenantMaster_PhoneNumber, 
            T.EmailAddress AS TenantMaster_EmailAddress, 
            T.WebAddress AS TenantMaster_WebAddress, 
            CAST(T.LogType AS [Edm.Int32]) AS TenantMaster_LogType, 
            T.ServerUrl AS TenantMaster_ServerUrl, 
            T.RemoteBackupPath AS TenantMaster_RemoteBackupPath, 
            T.IsSingleUserMode AS TenantMaster_IsSingleUserMode, 
            T.AccessCode AS TenantMaster_AccessCode, 
            True AS _from0
        FROM TenantDbContext.Tenants AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.DatabaseBackupLog.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing DatabaseBackupLog
        [CodeFirstDatabaseSchema.DatabaseBackupLog](T1.DatabaseBackupLog_Id, T1.DatabaseBackupLog_TenantId, T1.DatabaseBackupLog_StartDate, T1.DatabaseBackupLog_FinishDate, T1.DatabaseBackupLog_LocalFilePath, T1.DatabaseBackupLog_LocalFileSize, T1.DatabaseBackupLog_IsPublished, T1.DatabaseBackupLog_RemoteServerPath, T1.DatabaseBackupLog_RemoteFileSize, T1.DatabaseBackupLog_IsBackupFailed, T1.DatabaseBackupLog_Exception)
    FROM (
        SELECT 
            T.Id AS DatabaseBackupLog_Id, 
            T.TenantId AS DatabaseBackupLog_TenantId, 
            T.StartDate AS DatabaseBackupLog_StartDate, 
            T.FinishDate AS DatabaseBackupLog_FinishDate, 
            T.LocalFilePath AS DatabaseBackupLog_LocalFilePath, 
            T.LocalFileSize AS DatabaseBackupLog_LocalFileSize, 
            T.IsPublished AS DatabaseBackupLog_IsPublished, 
            T.RemoteServerPath AS DatabaseBackupLog_RemoteServerPath, 
            T.RemoteFileSize AS DatabaseBackupLog_RemoteFileSize, 
            T.IsBackupFailed AS DatabaseBackupLog_IsBackupFailed, 
            T.Exception AS DatabaseBackupLog_Exception, 
            True AS _from0
        FROM TenantDbContext.BackupLogs AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.IntegrationEventMaster.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing IntegrationEventMaster
        [CodeFirstDatabaseSchema.IntegrationEventMaster](T1.IntegrationEventMaster_EventCode, T1.IntegrationEventMaster_Name, T1.IntegrationEventMaster_Description)
    FROM (
        SELECT 
            T.EventCode AS IntegrationEventMaster_EventCode, 
            T.Name AS IntegrationEventMaster_Name, 
            T.Description AS IntegrationEventMaster_Description, 
            True AS _from0
        FROM TenantDbContext.IntegrationEvents AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Subscriber.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Subscriber
        [CodeFirstDatabaseSchema.Subscriber](T1.Subscriber_Id, T1.Subscriber_Name, T1.Subscriber_OriginHost, T1.Subscriber_Token)
    FROM (
        SELECT 
            T.Id AS Subscriber_Id, 
            T.Name AS Subscriber_Name, 
            T.OriginHost AS Subscriber_OriginHost, 
            T.Token AS Subscriber_Token, 
            True AS _from0
        FROM TenantDbContext.Integrations AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.JobTrack.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing JobTrack
        [CodeFirstDatabaseSchema.JobTrack](T1.JobTrack_Id, T1.JobTrack_JobLogId, T1.JobTrack_EventLogId, T1.JobTrack_EventCode, T1.JobTrack_SenderId, T1.JobTrack_TenantId, T1.JobTrack_EventBody, T1.JobTrack_IsProcessed, T1.JobTrack_Error, T1.JobTrack_ProcessedTime)
    FROM (
        SELECT 
            T.Id AS JobTrack_Id, 
            T.JobLogId AS JobTrack_JobLogId, 
            T.EventLogId AS JobTrack_EventLogId, 
            T.EventCode AS JobTrack_EventCode, 
            T.SenderId AS JobTrack_SenderId, 
            T.TenantId AS JobTrack_TenantId, 
            T.EventBody AS JobTrack_EventBody, 
            T.IsProcessed AS JobTrack_IsProcessed, 
            T.Error AS JobTrack_Error, 
            T.ProcessedTime AS JobTrack_ProcessedTime, 
            True AS _from0
        FROM TenantDbContext.Jobs AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.TenantMasterApplication.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TenantMasterApplication
        [CodeFirstDatabaseSchema.TenantMasterApplication](T1.[TenantMasterApplication.TenantMaster_Id], T1.[TenantMasterApplication.Application_Id])
    FROM (
        SELECT 
            Key(T.TenantMaster_Applications_Source).Id AS [TenantMasterApplication.TenantMaster_Id], 
            Key(T.TenantMaster_Applications_Target).Id AS [TenantMasterApplication.Application_Id], 
            True AS _from0
        FROM TenantDbContext.TenantMaster_Applications AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SubscriberIntegrationEventMaster.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SubscriberIntegrationEventMaster
        [CodeFirstDatabaseSchema.SubscriberIntegrationEventMaster](T1.[SubscriberIntegrationEventMaster.Subscriber_Id], T1.[SubscriberIntegrationEventMaster.IntegrationEventMaster_EventCode])
    FROM (
        SELECT 
            Key(T.Subscriber_Events_Source).Id AS [SubscriberIntegrationEventMaster.Subscriber_Id], 
            Key(T.Subscriber_Events_Target).EventCode AS [SubscriberIntegrationEventMaster.IntegrationEventMaster_EventCode], 
            True AS _from0
        FROM TenantDbContext.Subscriber_Events AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.Applications.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Applications
        [Tenant.Models.Application](T1.Application_Id, T1.Application_ApplicationName, T1.Application_ApplicationType, T1.Application_IsActive)
    FROM (
        SELECT 
            T.Id AS Application_Id, 
            T.ApplicationName AS Application_ApplicationName, 
            CAST(T.ApplicationType AS [Tenant.Models.ApplicationCategory]) AS Application_ApplicationType, 
            T.IsActive AS Application_IsActive, 
            True AS _from0
        FROM CodeFirstDatabase.Application AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.Tenants.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Tenants
        [Tenant.Models.TenantMaster](T1.TenantMaster_Id, T1.TenantMaster_Name, T1.TenantMaster_ClientKey, T1.TenantMaster_Secret, T1.TenantMaster_IsActive, T1.TenantMaster_ConnectionString, T1.TenantMaster_PostalAddress, T1.TenantMaster_PANNo, T1.TenantMaster_PhoneNumber, T1.TenantMaster_EmailAddress, T1.TenantMaster_WebAddress, T1.TenantMaster_LogType, T1.TenantMaster_ServerUrl, T1.TenantMaster_RemoteBackupPath, T1.TenantMaster_IsSingleUserMode, T1.TenantMaster_AccessCode)
    FROM (
        SELECT 
            T.Id AS TenantMaster_Id, 
            T.Name AS TenantMaster_Name, 
            T.ClientKey AS TenantMaster_ClientKey, 
            T.Secret AS TenantMaster_Secret, 
            T.IsActive AS TenantMaster_IsActive, 
            T.ConnectionString AS TenantMaster_ConnectionString, 
            T.PostalAddress AS TenantMaster_PostalAddress, 
            T.PANNo AS TenantMaster_PANNo, 
            T.PhoneNumber AS TenantMaster_PhoneNumber, 
            T.EmailAddress AS TenantMaster_EmailAddress, 
            T.WebAddress AS TenantMaster_WebAddress, 
            CAST(T.LogType AS [Tenant.Models.LogType]) AS TenantMaster_LogType, 
            T.ServerUrl AS TenantMaster_ServerUrl, 
            T.RemoteBackupPath AS TenantMaster_RemoteBackupPath, 
            T.IsSingleUserMode AS TenantMaster_IsSingleUserMode, 
            T.AccessCode AS TenantMaster_AccessCode, 
            True AS _from0
        FROM CodeFirstDatabase.TenantMaster AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.BackupLogs.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing BackupLogs
        [Tenant.Models.DatabaseBackupLog](T1.DatabaseBackupLog_Id, T1.DatabaseBackupLog_TenantId, T1.DatabaseBackupLog_StartDate, T1.DatabaseBackupLog_FinishDate, T1.DatabaseBackupLog_LocalFilePath, T1.DatabaseBackupLog_LocalFileSize, T1.DatabaseBackupLog_IsPublished, T1.DatabaseBackupLog_RemoteServerPath, T1.DatabaseBackupLog_RemoteFileSize, T1.DatabaseBackupLog_IsBackupFailed, T1.DatabaseBackupLog_Exception)
    FROM (
        SELECT 
            T.Id AS DatabaseBackupLog_Id, 
            T.TenantId AS DatabaseBackupLog_TenantId, 
            T.StartDate AS DatabaseBackupLog_StartDate, 
            T.FinishDate AS DatabaseBackupLog_FinishDate, 
            T.LocalFilePath AS DatabaseBackupLog_LocalFilePath, 
            T.LocalFileSize AS DatabaseBackupLog_LocalFileSize, 
            T.IsPublished AS DatabaseBackupLog_IsPublished, 
            T.RemoteServerPath AS DatabaseBackupLog_RemoteServerPath, 
            T.RemoteFileSize AS DatabaseBackupLog_RemoteFileSize, 
            T.IsBackupFailed AS DatabaseBackupLog_IsBackupFailed, 
            T.Exception AS DatabaseBackupLog_Exception, 
            True AS _from0
        FROM CodeFirstDatabase.DatabaseBackupLog AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.IntegrationEvents.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing IntegrationEvents
        [Tenant.Models.IntegrationEventMaster](T1.IntegrationEventMaster_EventCode, T1.IntegrationEventMaster_Name, T1.IntegrationEventMaster_Description)
    FROM (
        SELECT 
            T.EventCode AS IntegrationEventMaster_EventCode, 
            T.Name AS IntegrationEventMaster_Name, 
            T.Description AS IntegrationEventMaster_Description, 
            True AS _from0
        FROM CodeFirstDatabase.IntegrationEventMaster AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.Integrations.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView14()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Integrations
        [Tenant.Models.Subscriber](T1.Subscriber_Id, T1.Subscriber_Name, T1.Subscriber_OriginHost, T1.Subscriber_Token)
    FROM (
        SELECT 
            T.Id AS Subscriber_Id, 
            T.Name AS Subscriber_Name, 
            T.OriginHost AS Subscriber_OriginHost, 
            T.Token AS Subscriber_Token, 
            True AS _from0
        FROM CodeFirstDatabase.Subscriber AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.Jobs.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView15()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Jobs
        [Tenant.Models.JobTrack](T1.JobTrack_Id, T1.JobTrack_JobLogId, T1.JobTrack_EventLogId, T1.JobTrack_EventCode, T1.JobTrack_SenderId, T1.JobTrack_TenantId, T1.JobTrack_EventBody, T1.JobTrack_IsProcessed, T1.JobTrack_Error, T1.JobTrack_ProcessedTime)
    FROM (
        SELECT 
            T.Id AS JobTrack_Id, 
            T.JobLogId AS JobTrack_JobLogId, 
            T.EventLogId AS JobTrack_EventLogId, 
            T.EventCode AS JobTrack_EventCode, 
            T.SenderId AS JobTrack_SenderId, 
            T.TenantId AS JobTrack_TenantId, 
            T.EventBody AS JobTrack_EventBody, 
            T.IsProcessed AS JobTrack_IsProcessed, 
            T.Error AS JobTrack_Error, 
            T.ProcessedTime AS JobTrack_ProcessedTime, 
            True AS _from0
        FROM CodeFirstDatabase.JobTrack AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.TenantMaster_Applications.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView16()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing TenantMaster_Applications
        [Tenant.Models.TenantMaster_Applications](T3.[TenantMaster_Applications.TenantMaster_Applications_Source], T3.[TenantMaster_Applications.TenantMaster_Applications_Target])
    FROM (
        SELECT -- Constructing TenantMaster_Applications_Source
            CreateRef(TenantDbContext.Tenants, row(T2.[TenantMaster_Applications.TenantMaster_Applications_Source.Id]), [Tenant.Models.TenantMaster]) AS [TenantMaster_Applications.TenantMaster_Applications_Source], 
            T2.[TenantMaster_Applications.TenantMaster_Applications_Target]
        FROM (
            SELECT -- Constructing TenantMaster_Applications_Target
                T1.[TenantMaster_Applications.TenantMaster_Applications_Source.Id], 
                CreateRef(TenantDbContext.Applications, row(T1.[TenantMaster_Applications.TenantMaster_Applications_Target.Id]), [Tenant.Models.Application]) AS [TenantMaster_Applications.TenantMaster_Applications_Target]
            FROM (
                SELECT 
                    T.TenantMaster_Id AS [TenantMaster_Applications.TenantMaster_Applications_Source.Id], 
                    T.Application_Id AS [TenantMaster_Applications.TenantMaster_Applications_Target.Id], 
                    True AS _from0
                FROM CodeFirstDatabase.TenantMasterApplication AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.Subscriber_Events.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView17()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Subscriber_Events
        [Tenant.Models.Subscriber_Events](T3.[Subscriber_Events.Subscriber_Events_Source], T3.[Subscriber_Events.Subscriber_Events_Target])
    FROM (
        SELECT -- Constructing Subscriber_Events_Source
            CreateRef(TenantDbContext.Integrations, row(T2.[Subscriber_Events.Subscriber_Events_Source.Id]), [Tenant.Models.Subscriber]) AS [Subscriber_Events.Subscriber_Events_Source], 
            T2.[Subscriber_Events.Subscriber_Events_Target]
        FROM (
            SELECT -- Constructing Subscriber_Events_Target
                T1.[Subscriber_Events.Subscriber_Events_Source.Id], 
                CreateRef(TenantDbContext.IntegrationEvents, row(T1.[Subscriber_Events.Subscriber_Events_Target.EventCode]), [Tenant.Models.IntegrationEventMaster]) AS [Subscriber_Events.Subscriber_Events_Target]
            FROM (
                SELECT 
                    T.Subscriber_Id AS [Subscriber_Events.Subscriber_Events_Source.Id], 
                    T.IntegrationEventMaster_EventCode AS [Subscriber_Events.Subscriber_Events_Target.EventCode], 
                    True AS _from0
                FROM CodeFirstDatabase.SubscriberIntegrationEventMaster AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.FuelCompany.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView18()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing FuelCompany
        [CodeFirstDatabaseSchema.FuelCompany](T1.FuelCompany_CompanyCode, T1.FuelCompany_CompanyName)
    FROM (
        SELECT 
            T.CompanyCode AS FuelCompany_CompanyCode, 
            T.CompanyName AS FuelCompany_CompanyName, 
            True AS _from0
        FROM TenantDbContext.FuelCompanies AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.IOCPump.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView19()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing IOCPump
        [CodeFirstDatabaseSchema.IOCPump](T1.IOCPump_PumpId, T1.IOCPump_PumpName, T1.IOCPump_PumpCode, T1.IOCPump_Latitude, T1.IOCPump_Longitude, T1.IOCPump_Address, T1.IOCPump_PetrolPrice, T1.IOCPump_DieselPrice, T1.IOCPump_Owner, T1.IOCPump_OwnerPhone, T1.IOCPump_District, T1.IOCPump_AreaSalesOfficeContact, T1.IOCPump_StateId, T1.IOCPump_CompanyCode, T1.IOCPump_LastRateUpdated, T1.IOCPump_LastError, T1.IOCPump_LastErrorTime, T1.IOCPump_TownId)
    FROM (
        SELECT 
            T.PumpId AS IOCPump_PumpId, 
            T.PumpName AS IOCPump_PumpName, 
            T.PumpCode AS IOCPump_PumpCode, 
            T.Latitude AS IOCPump_Latitude, 
            T.Longitude AS IOCPump_Longitude, 
            T.Address AS IOCPump_Address, 
            T.PetrolPrice AS IOCPump_PetrolPrice, 
            T.DieselPrice AS IOCPump_DieselPrice, 
            T.Owner AS IOCPump_Owner, 
            T.OwnerPhone AS IOCPump_OwnerPhone, 
            T.District AS IOCPump_District, 
            T.AreaSalesOfficeContact AS IOCPump_AreaSalesOfficeContact, 
            T.StateId AS IOCPump_StateId, 
            T.CompanyCode AS IOCPump_CompanyCode, 
            T.LastRateUpdated AS IOCPump_LastRateUpdated, 
            T.LastError AS IOCPump_LastError, 
            T.LastErrorTime AS IOCPump_LastErrorTime, 
            T.TownId AS IOCPump_TownId, 
            True AS _from0
        FROM TenantDbContext.Pumps AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.RateLog.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView20()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RateLog
        [CodeFirstDatabaseSchema.RateLog](T1.RateLog_Id, T1.RateLog_PumpId, T1.RateLog_TownCode, T1.RateLog_LogDate, T1.RateLog_PetrolPrice, T1.RateLog_DieselPrice)
    FROM (
        SELECT 
            T.Id AS RateLog_Id, 
            T.PumpId AS RateLog_PumpId, 
            T.TownCode AS RateLog_TownCode, 
            T.LogDate AS RateLog_LogDate, 
            T.PetrolPrice AS RateLog_PetrolPrice, 
            T.DieselPrice AS RateLog_DieselPrice, 
            True AS _from0
        FROM TenantDbContext.RateLogs AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.HPCLTown.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView21()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing HPCLTown
        [CodeFirstDatabaseSchema.HPCLTown](T1.HPCLTown_Id, T1.HPCLTown_StateId, T1.HPCLTown_TownCode, T1.HPCLTown_TownName, T1.HPCLTown_Latitude, T1.HPCLTown_Longitude, T1.HPCLTown_PetrolPrice, T1.HPCLTown_DieselPrice, T1.HPCLTown_LastRateUpdated, T1.HPCLTown_LastError, T1.HPCLTown_LastErrorTime)
    FROM (
        SELECT 
            T.Id AS HPCLTown_Id, 
            T.StateId AS HPCLTown_StateId, 
            T.TownCode AS HPCLTown_TownCode, 
            T.TownName AS HPCLTown_TownName, 
            T.Latitude AS HPCLTown_Latitude, 
            T.Longitude AS HPCLTown_Longitude, 
            T.PetrolPrice AS HPCLTown_PetrolPrice, 
            T.DieselPrice AS HPCLTown_DieselPrice, 
            T.LastRateUpdated AS HPCLTown_LastRateUpdated, 
            T.LastError AS HPCLTown_LastError, 
            T.LastErrorTime AS HPCLTown_LastErrorTime, 
            True AS _from0
        FROM TenantDbContext.Towns AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.StateMaster.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView22()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing StateMaster
        [CodeFirstDatabaseSchema.StateMaster](T1.StateMaster_Id, T1.StateMaster_StateCode, T1.StateMaster_StateName, T1.StateMaster_CompanyCode, T1.StateMaster_LastRateUpdated, T1.StateMaster_LastError, T1.StateMaster_LastErrorTime)
    FROM (
        SELECT 
            T.Id AS StateMaster_Id, 
            T.StateCode AS StateMaster_StateCode, 
            T.StateName AS StateMaster_StateName, 
            T.CompanyCode AS StateMaster_CompanyCode, 
            T.LastRateUpdated AS StateMaster_LastRateUpdated, 
            T.LastError AS StateMaster_LastError, 
            T.LastErrorTime AS StateMaster_LastErrorTime, 
            True AS _from0
        FROM TenantDbContext.States AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.FuelCompanies.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView23()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing FuelCompanies
        [Tenant.Models.FuelCompany](T1.FuelCompany_CompanyCode, T1.FuelCompany_CompanyName)
    FROM (
        SELECT 
            T.CompanyCode AS FuelCompany_CompanyCode, 
            T.CompanyName AS FuelCompany_CompanyName, 
            True AS _from0
        FROM CodeFirstDatabase.FuelCompany AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.Pumps.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView24()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Pumps
        [Tenant.Models.IOCPump](T1.IOCPump_PumpId, T1.IOCPump_PumpName, T1.IOCPump_PumpCode, T1.IOCPump_Latitude, T1.IOCPump_Longitude, T1.IOCPump_Address, T1.IOCPump_PetrolPrice, T1.IOCPump_DieselPrice, T1.IOCPump_Owner, T1.IOCPump_OwnerPhone, T1.IOCPump_District, T1.IOCPump_AreaSalesOfficeContact, T1.IOCPump_StateId, T1.IOCPump_CompanyCode, T1.IOCPump_LastRateUpdated, T1.IOCPump_LastError, T1.IOCPump_LastErrorTime, T1.IOCPump_TownId)
    FROM (
        SELECT 
            T.PumpId AS IOCPump_PumpId, 
            T.PumpName AS IOCPump_PumpName, 
            T.PumpCode AS IOCPump_PumpCode, 
            T.Latitude AS IOCPump_Latitude, 
            T.Longitude AS IOCPump_Longitude, 
            T.Address AS IOCPump_Address, 
            T.PetrolPrice AS IOCPump_PetrolPrice, 
            T.DieselPrice AS IOCPump_DieselPrice, 
            T.Owner AS IOCPump_Owner, 
            T.OwnerPhone AS IOCPump_OwnerPhone, 
            T.District AS IOCPump_District, 
            T.AreaSalesOfficeContact AS IOCPump_AreaSalesOfficeContact, 
            T.StateId AS IOCPump_StateId, 
            T.CompanyCode AS IOCPump_CompanyCode, 
            T.LastRateUpdated AS IOCPump_LastRateUpdated, 
            T.LastError AS IOCPump_LastError, 
            T.LastErrorTime AS IOCPump_LastErrorTime, 
            T.TownId AS IOCPump_TownId, 
            True AS _from0
        FROM CodeFirstDatabase.IOCPump AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.RateLogs.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView25()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing RateLogs
        [Tenant.Models.RateLog](T1.RateLog_Id, T1.RateLog_PumpId, T1.RateLog_TownCode, T1.RateLog_LogDate, T1.RateLog_PetrolPrice, T1.RateLog_DieselPrice)
    FROM (
        SELECT 
            T.Id AS RateLog_Id, 
            T.PumpId AS RateLog_PumpId, 
            T.TownCode AS RateLog_TownCode, 
            T.LogDate AS RateLog_LogDate, 
            T.PetrolPrice AS RateLog_PetrolPrice, 
            T.DieselPrice AS RateLog_DieselPrice, 
            True AS _from0
        FROM CodeFirstDatabase.RateLog AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.Towns.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView26()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Towns
        [Tenant.Models.HPCLTown](T1.HPCLTown_Id, T1.HPCLTown_StateId, T1.HPCLTown_TownCode, T1.HPCLTown_TownName, T1.HPCLTown_Latitude, T1.HPCLTown_Longitude, T1.HPCLTown_PetrolPrice, T1.HPCLTown_DieselPrice, T1.HPCLTown_LastRateUpdated, T1.HPCLTown_LastError, T1.HPCLTown_LastErrorTime)
    FROM (
        SELECT 
            T.Id AS HPCLTown_Id, 
            T.StateId AS HPCLTown_StateId, 
            T.TownCode AS HPCLTown_TownCode, 
            T.TownName AS HPCLTown_TownName, 
            T.Latitude AS HPCLTown_Latitude, 
            T.Longitude AS HPCLTown_Longitude, 
            T.PetrolPrice AS HPCLTown_PetrolPrice, 
            T.DieselPrice AS HPCLTown_DieselPrice, 
            T.LastRateUpdated AS HPCLTown_LastRateUpdated, 
            T.LastError AS HPCLTown_LastError, 
            T.LastErrorTime AS HPCLTown_LastErrorTime, 
            True AS _from0
        FROM CodeFirstDatabase.HPCLTown AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for TenantDbContext.States.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView27()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing States
        [Tenant.Models.StateMaster](T1.StateMaster_Id, T1.StateMaster_StateCode, T1.StateMaster_StateName, T1.StateMaster_CompanyCode, T1.StateMaster_LastRateUpdated, T1.StateMaster_LastError, T1.StateMaster_LastErrorTime)
    FROM (
        SELECT 
            T.Id AS StateMaster_Id, 
            T.StateCode AS StateMaster_StateCode, 
            T.StateName AS StateMaster_StateName, 
            T.CompanyCode AS StateMaster_CompanyCode, 
            T.LastRateUpdated AS StateMaster_LastRateUpdated, 
            T.LastError AS StateMaster_LastError, 
            T.LastErrorTime AS StateMaster_LastErrorTime, 
            True AS _from0
        FROM CodeFirstDatabase.StateMaster AS T
    ) AS T1");
        }
    }
}
