//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackoApi.Service.Bajaj.Data {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersData", ConfigurationName="Bajaj.Data.TransportersData_OUT")]
    public interface TransportersData_OUT {
        
        // CODEGEN: Generating message contract since the operation TransportersData_OUT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TrackoApi.Service.Bajaj.Data.TransportersData_OUTResponse TransportersData_OUT(TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        System.Threading.Tasks.Task<TrackoApi.Service.Bajaj.Data.TransportersData_OUTResponse> TransportersData_OUTAsync(TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersDataRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RequestTokenID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
                this.RaisePropertyChanged("Header");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransportersResponseDataZSD_DAM_DTL_STG[] zSD_DAM_DTL_STGField;
        
        private TransportersResponseDataZSD_DEL_DET_STG[] zSD_DEL_DET_STGField;
        
        private TransportersResponseDataZSD_DTAG_STG[] zSD_DTAG_STGField;
        
        private TransportersResponseDataZSD_FRT_DTL_STG[] zSD_FRT_DTL_STGField;
        
        private TransportersResponseDataZSD_LR_DET_STG[] zSD_LR_DET_STGField;
        
        private TransportersResponseDataZSD_SRT_DTL_STG[] zSD_SRT_DTL_STGField;
        
        private TransportersResponseDataZSD_LR_HDR_DTL[] zSD_LR_HDR_DTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZSD_DAM_DTL_STG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TransportersResponseDataZSD_DAM_DTL_STG[] ZSD_DAM_DTL_STG {
            get {
                return this.zSD_DAM_DTL_STGField;
            }
            set {
                this.zSD_DAM_DTL_STGField = value;
                this.RaisePropertyChanged("ZSD_DAM_DTL_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZSD_DEL_DET_STG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public TransportersResponseDataZSD_DEL_DET_STG[] ZSD_DEL_DET_STG {
            get {
                return this.zSD_DEL_DET_STGField;
            }
            set {
                this.zSD_DEL_DET_STGField = value;
                this.RaisePropertyChanged("ZSD_DEL_DET_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZSD_DTAG_STG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public TransportersResponseDataZSD_DTAG_STG[] ZSD_DTAG_STG {
            get {
                return this.zSD_DTAG_STGField;
            }
            set {
                this.zSD_DTAG_STGField = value;
                this.RaisePropertyChanged("ZSD_DTAG_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZSD_FRT_DTL_STG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public TransportersResponseDataZSD_FRT_DTL_STG[] ZSD_FRT_DTL_STG {
            get {
                return this.zSD_FRT_DTL_STGField;
            }
            set {
                this.zSD_FRT_DTL_STGField = value;
                this.RaisePropertyChanged("ZSD_FRT_DTL_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZSD_LR_DET_STG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public TransportersResponseDataZSD_LR_DET_STG[] ZSD_LR_DET_STG {
            get {
                return this.zSD_LR_DET_STGField;
            }
            set {
                this.zSD_LR_DET_STGField = value;
                this.RaisePropertyChanged("ZSD_LR_DET_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZSD_SRT_DTL_STG", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public TransportersResponseDataZSD_SRT_DTL_STG[] ZSD_SRT_DTL_STG {
            get {
                return this.zSD_SRT_DTL_STGField;
            }
            set {
                this.zSD_SRT_DTL_STGField = value;
                this.RaisePropertyChanged("ZSD_SRT_DTL_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ZSD_LR_HDR_DTL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public TransportersResponseDataZSD_LR_HDR_DTL[] ZSD_LR_HDR_DTL {
            get {
                return this.zSD_LR_HDR_DTLField;
            }
            set {
                this.zSD_LR_HDR_DTLField = value;
                this.RaisePropertyChanged("ZSD_LR_HDR_DTL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseDataZSD_DAM_DTL_STG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kUNNR_TField;
        
        private string tRIP_NOField;
        
        private string lR_NOField;
        
        private string vBELNField;
        
        private string fKDATField;
        
        private string wERKSField;
        
        private string tRANS_NAMEField;
        
        private string aDD01Field;
        
        private string cITYField;
        
        private string tRIP_DISTField;
        
        private string kUNNR_DField;
        
        private string dEALER_NAMEField;
        
        private string bILL_QTYField;
        
        private string tRIP_FREIGHTField;
        
        private string mAJOR_DAM_QTYField;
        
        private string mINOR_DAM_QTYField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KUNNR_T {
            get {
                return this.kUNNR_TField;
            }
            set {
                this.kUNNR_TField = value;
                this.RaisePropertyChanged("KUNNR_T");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRIP_NO {
            get {
                return this.tRIP_NOField;
            }
            set {
                this.tRIP_NOField = value;
                this.RaisePropertyChanged("TRIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LR_NO {
            get {
                return this.lR_NOField;
            }
            set {
                this.lR_NOField = value;
                this.RaisePropertyChanged("LR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
                this.RaisePropertyChanged("VBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FKDAT {
            get {
                return this.fKDATField;
            }
            set {
                this.fKDATField = value;
                this.RaisePropertyChanged("FKDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TRANS_NAME {
            get {
                return this.tRANS_NAMEField;
            }
            set {
                this.tRANS_NAMEField = value;
                this.RaisePropertyChanged("TRANS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ADD01 {
            get {
                return this.aDD01Field;
            }
            set {
                this.aDD01Field = value;
                this.RaisePropertyChanged("ADD01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TRIP_DIST {
            get {
                return this.tRIP_DISTField;
            }
            set {
                this.tRIP_DISTField = value;
                this.RaisePropertyChanged("TRIP_DIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string KUNNR_D {
            get {
                return this.kUNNR_DField;
            }
            set {
                this.kUNNR_DField = value;
                this.RaisePropertyChanged("KUNNR_D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DEALER_NAME {
            get {
                return this.dEALER_NAMEField;
            }
            set {
                this.dEALER_NAMEField = value;
                this.RaisePropertyChanged("DEALER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string BILL_QTY {
            get {
                return this.bILL_QTYField;
            }
            set {
                this.bILL_QTYField = value;
                this.RaisePropertyChanged("BILL_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string TRIP_FREIGHT {
            get {
                return this.tRIP_FREIGHTField;
            }
            set {
                this.tRIP_FREIGHTField = value;
                this.RaisePropertyChanged("TRIP_FREIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MAJOR_DAM_QTY {
            get {
                return this.mAJOR_DAM_QTYField;
            }
            set {
                this.mAJOR_DAM_QTYField = value;
                this.RaisePropertyChanged("MAJOR_DAM_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MINOR_DAM_QTY {
            get {
                return this.mINOR_DAM_QTYField;
            }
            set {
                this.mINOR_DAM_QTYField = value;
                this.RaisePropertyChanged("MINOR_DAM_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseDataZSD_DEL_DET_STG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kUNNR_TField;
        
        private string tRIP_NOField;
        
        private string lR_NOField;
        
        private string vBELNField;
        
        private string fKDATField;
        
        private string wERKSField;
        
        private string tRANS_NAMEField;
        
        private string aDD01Field;
        
        private string cITYField;
        
        private string tRIP_DISTField;
        
        private string kUNNR_DField;
        
        private string dEALER_NAMEField;
        
        private string eXP_DATEField;
        
        private string rEP_DATEField;
        
        private string rEP_TIMEField;
        
        private string uNLOAD_DATEField;
        
        private string uNLOAD_TIMEField;
        
        private string pERCENT_LOADField;
        
        private string tRANSIT_PENALTYField;
        
        private string dEALER_DETENTIONField;
        
        private string sGUIDField;
        
        private string tGUIDField;
        
        private string cREATED_DATEField;
        
        private string cREATED_TIMEField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string uPD_DATEField;
        
        private string uPD_TIMEField;
        
        private string uPD_USERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KUNNR_T {
            get {
                return this.kUNNR_TField;
            }
            set {
                this.kUNNR_TField = value;
                this.RaisePropertyChanged("KUNNR_T");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRIP_NO {
            get {
                return this.tRIP_NOField;
            }
            set {
                this.tRIP_NOField = value;
                this.RaisePropertyChanged("TRIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LR_NO {
            get {
                return this.lR_NOField;
            }
            set {
                this.lR_NOField = value;
                this.RaisePropertyChanged("LR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
                this.RaisePropertyChanged("VBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FKDAT {
            get {
                return this.fKDATField;
            }
            set {
                this.fKDATField = value;
                this.RaisePropertyChanged("FKDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TRANS_NAME {
            get {
                return this.tRANS_NAMEField;
            }
            set {
                this.tRANS_NAMEField = value;
                this.RaisePropertyChanged("TRANS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ADD01 {
            get {
                return this.aDD01Field;
            }
            set {
                this.aDD01Field = value;
                this.RaisePropertyChanged("ADD01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TRIP_DIST {
            get {
                return this.tRIP_DISTField;
            }
            set {
                this.tRIP_DISTField = value;
                this.RaisePropertyChanged("TRIP_DIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string KUNNR_D {
            get {
                return this.kUNNR_DField;
            }
            set {
                this.kUNNR_DField = value;
                this.RaisePropertyChanged("KUNNR_D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string DEALER_NAME {
            get {
                return this.dEALER_NAMEField;
            }
            set {
                this.dEALER_NAMEField = value;
                this.RaisePropertyChanged("DEALER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string EXP_DATE {
            get {
                return this.eXP_DATEField;
            }
            set {
                this.eXP_DATEField = value;
                this.RaisePropertyChanged("EXP_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string REP_DATE {
            get {
                return this.rEP_DATEField;
            }
            set {
                this.rEP_DATEField = value;
                this.RaisePropertyChanged("REP_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string REP_TIME {
            get {
                return this.rEP_TIMEField;
            }
            set {
                this.rEP_TIMEField = value;
                this.RaisePropertyChanged("REP_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string UNLOAD_DATE {
            get {
                return this.uNLOAD_DATEField;
            }
            set {
                this.uNLOAD_DATEField = value;
                this.RaisePropertyChanged("UNLOAD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string UNLOAD_TIME {
            get {
                return this.uNLOAD_TIMEField;
            }
            set {
                this.uNLOAD_TIMEField = value;
                this.RaisePropertyChanged("UNLOAD_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string PERCENT_LOAD {
            get {
                return this.pERCENT_LOADField;
            }
            set {
                this.pERCENT_LOADField = value;
                this.RaisePropertyChanged("PERCENT_LOAD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string TRANSIT_PENALTY {
            get {
                return this.tRANSIT_PENALTYField;
            }
            set {
                this.tRANSIT_PENALTYField = value;
                this.RaisePropertyChanged("TRANSIT_PENALTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string DEALER_DETENTION {
            get {
                return this.dEALER_DETENTIONField;
            }
            set {
                this.dEALER_DETENTIONField = value;
                this.RaisePropertyChanged("DEALER_DETENTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string CREATED_DATE {
            get {
                return this.cREATED_DATEField;
            }
            set {
                this.cREATED_DATEField = value;
                this.RaisePropertyChanged("CREATED_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CREATED_TIME {
            get {
                return this.cREATED_TIMEField;
            }
            set {
                this.cREATED_TIMEField = value;
                this.RaisePropertyChanged("CREATED_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string UPD_DATE {
            get {
                return this.uPD_DATEField;
            }
            set {
                this.uPD_DATEField = value;
                this.RaisePropertyChanged("UPD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string UPD_TIME {
            get {
                return this.uPD_TIMEField;
            }
            set {
                this.uPD_TIMEField = value;
                this.RaisePropertyChanged("UPD_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string UPD_USER {
            get {
                return this.uPD_USERField;
            }
            set {
                this.uPD_USERField = value;
                this.RaisePropertyChanged("UPD_USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseDataZSD_DTAG_STG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kUNNR_TField;
        
        private string aDD01Field;
        
        private string cREATED_DATEField;
        
        private string cREATED_TIMEField;
        
        private string tRANS_NAMEField;
        
        private string tRK_STATUSField;
        
        private string uPD_DATEField;
        
        private string uPD_TIMEField;
        
        private string uPD_USERField;
        
        private string sGUIDField;
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KUNNR_T {
            get {
                return this.kUNNR_TField;
            }
            set {
                this.kUNNR_TField = value;
                this.RaisePropertyChanged("KUNNR_T");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ADD01 {
            get {
                return this.aDD01Field;
            }
            set {
                this.aDD01Field = value;
                this.RaisePropertyChanged("ADD01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CREATED_DATE {
            get {
                return this.cREATED_DATEField;
            }
            set {
                this.cREATED_DATEField = value;
                this.RaisePropertyChanged("CREATED_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CREATED_TIME {
            get {
                return this.cREATED_TIMEField;
            }
            set {
                this.cREATED_TIMEField = value;
                this.RaisePropertyChanged("CREATED_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANS_NAME {
            get {
                return this.tRANS_NAMEField;
            }
            set {
                this.tRANS_NAMEField = value;
                this.RaisePropertyChanged("TRANS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TRK_STATUS {
            get {
                return this.tRK_STATUSField;
            }
            set {
                this.tRK_STATUSField = value;
                this.RaisePropertyChanged("TRK_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string UPD_DATE {
            get {
                return this.uPD_DATEField;
            }
            set {
                this.uPD_DATEField = value;
                this.RaisePropertyChanged("UPD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string UPD_TIME {
            get {
                return this.uPD_TIMEField;
            }
            set {
                this.uPD_TIMEField = value;
                this.RaisePropertyChanged("UPD_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string UPD_USER {
            get {
                return this.uPD_USERField;
            }
            set {
                this.uPD_USERField = value;
                this.RaisePropertyChanged("UPD_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseDataZSD_FRT_DTL_STG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kUNNR_TField;
        
        private string tRIP_NOField;
        
        private string lR_NOField;
        
        private string vBELNField;
        
        private string pOSNRField;
        
        private string gOODS_DESCField;
        
        private string fKDATField;
        
        private string wERKSField;
        
        private string tRANS_NAMEField;
        
        private string aDD01Field;
        
        private string cITYField;
        
        private string tRIP_DISTField;
        
        private string kUNNR_DField;
        
        private string dEALER_NAMEField;
        
        private string bILL_QTYField;
        
        private string mPBASEField;
        
        private string cMVR_STATUSField;
        
        private string rATEField;
        
        private string fREIGHTField;
        
        private string cLUSTER_FREIGHTField;
        
        private string tOTAL_FREIGHTField;
        
        private string sGUIDField;
        
        private string tGUIDField;
        
        private string cREATED_DATEField;
        
        private string cREATED_TIMEField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string uPD_DATEField;
        
        private string uPD_TIMEField;
        
        private string uPD_USERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KUNNR_T {
            get {
                return this.kUNNR_TField;
            }
            set {
                this.kUNNR_TField = value;
                this.RaisePropertyChanged("KUNNR_T");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRIP_NO {
            get {
                return this.tRIP_NOField;
            }
            set {
                this.tRIP_NOField = value;
                this.RaisePropertyChanged("TRIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LR_NO {
            get {
                return this.lR_NOField;
            }
            set {
                this.lR_NOField = value;
                this.RaisePropertyChanged("LR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
                this.RaisePropertyChanged("VBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string POSNR {
            get {
                return this.pOSNRField;
            }
            set {
                this.pOSNRField = value;
                this.RaisePropertyChanged("POSNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string GOODS_DESC {
            get {
                return this.gOODS_DESCField;
            }
            set {
                this.gOODS_DESCField = value;
                this.RaisePropertyChanged("GOODS_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FKDAT {
            get {
                return this.fKDATField;
            }
            set {
                this.fKDATField = value;
                this.RaisePropertyChanged("FKDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string TRANS_NAME {
            get {
                return this.tRANS_NAMEField;
            }
            set {
                this.tRANS_NAMEField = value;
                this.RaisePropertyChanged("TRANS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ADD01 {
            get {
                return this.aDD01Field;
            }
            set {
                this.aDD01Field = value;
                this.RaisePropertyChanged("ADD01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string TRIP_DIST {
            get {
                return this.tRIP_DISTField;
            }
            set {
                this.tRIP_DISTField = value;
                this.RaisePropertyChanged("TRIP_DIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string KUNNR_D {
            get {
                return this.kUNNR_DField;
            }
            set {
                this.kUNNR_DField = value;
                this.RaisePropertyChanged("KUNNR_D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string DEALER_NAME {
            get {
                return this.dEALER_NAMEField;
            }
            set {
                this.dEALER_NAMEField = value;
                this.RaisePropertyChanged("DEALER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string BILL_QTY {
            get {
                return this.bILL_QTYField;
            }
            set {
                this.bILL_QTYField = value;
                this.RaisePropertyChanged("BILL_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MPBASE {
            get {
                return this.mPBASEField;
            }
            set {
                this.mPBASEField = value;
                this.RaisePropertyChanged("MPBASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string CMVR_STATUS {
            get {
                return this.cMVR_STATUSField;
            }
            set {
                this.cMVR_STATUSField = value;
                this.RaisePropertyChanged("CMVR_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string RATE {
            get {
                return this.rATEField;
            }
            set {
                this.rATEField = value;
                this.RaisePropertyChanged("RATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string FREIGHT {
            get {
                return this.fREIGHTField;
            }
            set {
                this.fREIGHTField = value;
                this.RaisePropertyChanged("FREIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CLUSTER_FREIGHT {
            get {
                return this.cLUSTER_FREIGHTField;
            }
            set {
                this.cLUSTER_FREIGHTField = value;
                this.RaisePropertyChanged("CLUSTER_FREIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string TOTAL_FREIGHT {
            get {
                return this.tOTAL_FREIGHTField;
            }
            set {
                this.tOTAL_FREIGHTField = value;
                this.RaisePropertyChanged("TOTAL_FREIGHT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string CREATED_DATE {
            get {
                return this.cREATED_DATEField;
            }
            set {
                this.cREATED_DATEField = value;
                this.RaisePropertyChanged("CREATED_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string CREATED_TIME {
            get {
                return this.cREATED_TIMEField;
            }
            set {
                this.cREATED_TIMEField = value;
                this.RaisePropertyChanged("CREATED_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string UPD_DATE {
            get {
                return this.uPD_DATEField;
            }
            set {
                this.uPD_DATEField = value;
                this.RaisePropertyChanged("UPD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string UPD_TIME {
            get {
                return this.uPD_TIMEField;
            }
            set {
                this.uPD_TIMEField = value;
                this.RaisePropertyChanged("UPD_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string UPD_USER {
            get {
                return this.uPD_USERField;
            }
            set {
                this.uPD_USERField = value;
                this.RaisePropertyChanged("UPD_USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseDataZSD_LR_DET_STG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kUNNR_TField;
        
        private string tRIP_NOField;
        
        private string vBELNField;
        
        private string mATNRField;
        
        private string gOODS_DESCField;
        
        private string fKDATField;
        
        private string wERKSField;
        
        private string tRANS_NAMEField;
        
        private string aDD01Field;
        
        private string kUNNR_DField;
        
        private string dEALER_NAMEField;
        
        private string bILL_QTYField;
        
        private string lR_NOField;
        
        private string eWAY_BILL_NOField;
        
        private string eWAY_BILL_DATEField;
        
        private string eWAY_BILL_TIMEField;
        
        private string eWAY_BILL_VALID_DATEField;
        
        private string sGUIDField;
        
        private string tGUIDField;
        
        private string cREATED_DATEField;
        
        private string cREATED_TIMEField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string uPD_DATEField;
        
        private string uPD_TIMEField;
        
        private string uPD_USERField;
        
        private string fKSTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KUNNR_T {
            get {
                return this.kUNNR_TField;
            }
            set {
                this.kUNNR_TField = value;
                this.RaisePropertyChanged("KUNNR_T");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRIP_NO {
            get {
                return this.tRIP_NOField;
            }
            set {
                this.tRIP_NOField = value;
                this.RaisePropertyChanged("TRIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
                this.RaisePropertyChanged("VBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
                this.RaisePropertyChanged("MATNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string GOODS_DESC {
            get {
                return this.gOODS_DESCField;
            }
            set {
                this.gOODS_DESCField = value;
                this.RaisePropertyChanged("GOODS_DESC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FKDAT {
            get {
                return this.fKDATField;
            }
            set {
                this.fKDATField = value;
                this.RaisePropertyChanged("FKDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TRANS_NAME {
            get {
                return this.tRANS_NAMEField;
            }
            set {
                this.tRANS_NAMEField = value;
                this.RaisePropertyChanged("TRANS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ADD01 {
            get {
                return this.aDD01Field;
            }
            set {
                this.aDD01Field = value;
                this.RaisePropertyChanged("ADD01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string KUNNR_D {
            get {
                return this.kUNNR_DField;
            }
            set {
                this.kUNNR_DField = value;
                this.RaisePropertyChanged("KUNNR_D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string DEALER_NAME {
            get {
                return this.dEALER_NAMEField;
            }
            set {
                this.dEALER_NAMEField = value;
                this.RaisePropertyChanged("DEALER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string BILL_QTY {
            get {
                return this.bILL_QTYField;
            }
            set {
                this.bILL_QTYField = value;
                this.RaisePropertyChanged("BILL_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string LR_NO {
            get {
                return this.lR_NOField;
            }
            set {
                this.lR_NOField = value;
                this.RaisePropertyChanged("LR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string EWAY_BILL_NO {
            get {
                return this.eWAY_BILL_NOField;
            }
            set {
                this.eWAY_BILL_NOField = value;
                this.RaisePropertyChanged("EWAY_BILL_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string EWAY_BILL_DATE {
            get {
                return this.eWAY_BILL_DATEField;
            }
            set {
                this.eWAY_BILL_DATEField = value;
                this.RaisePropertyChanged("EWAY_BILL_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string EWAY_BILL_TIME {
            get {
                return this.eWAY_BILL_TIMEField;
            }
            set {
                this.eWAY_BILL_TIMEField = value;
                this.RaisePropertyChanged("EWAY_BILL_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string EWAY_BILL_VALID_DATE {
            get {
                return this.eWAY_BILL_VALID_DATEField;
            }
            set {
                this.eWAY_BILL_VALID_DATEField = value;
                this.RaisePropertyChanged("EWAY_BILL_VALID_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CREATED_DATE {
            get {
                return this.cREATED_DATEField;
            }
            set {
                this.cREATED_DATEField = value;
                this.RaisePropertyChanged("CREATED_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string CREATED_TIME {
            get {
                return this.cREATED_TIMEField;
            }
            set {
                this.cREATED_TIMEField = value;
                this.RaisePropertyChanged("CREATED_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string UPD_DATE {
            get {
                return this.uPD_DATEField;
            }
            set {
                this.uPD_DATEField = value;
                this.RaisePropertyChanged("UPD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string UPD_TIME {
            get {
                return this.uPD_TIMEField;
            }
            set {
                this.uPD_TIMEField = value;
                this.RaisePropertyChanged("UPD_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string UPD_USER {
            get {
                return this.uPD_USERField;
            }
            set {
                this.uPD_USERField = value;
                this.RaisePropertyChanged("UPD_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string FKSTO {
            get {
                return this.fKSTOField;
            }
            set {
                this.fKSTOField = value;
                this.RaisePropertyChanged("FKSTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseDataZSD_SRT_DTL_STG : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kUNNR_TField;
        
        private string tRIP_NOField;
        
        private string lR_NOField;
        
        private string vBELNField;
        
        private string sHORT_PARTField;
        
        private string fKDATField;
        
        private string wERKSField;
        
        private string tRANS_NAMEField;
        
        private string aDD01Field;
        
        private string cITYField;
        
        private string tRIP_DISTField;
        
        private string kUNNR_DField;
        
        private string dEALER_NAMEField;
        
        private string sHORT_NAMEField;
        
        private string sHORT_QTYField;
        
        private string bILL_QTYField;
        
        private string sGUIDField;
        
        private string tGUIDField;
        
        private string cREATED_DATEField;
        
        private string cREATED_TIMEField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string uPD_DATEField;
        
        private string uPD_TIMEField;
        
        private string uPD_USERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KUNNR_T {
            get {
                return this.kUNNR_TField;
            }
            set {
                this.kUNNR_TField = value;
                this.RaisePropertyChanged("KUNNR_T");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRIP_NO {
            get {
                return this.tRIP_NOField;
            }
            set {
                this.tRIP_NOField = value;
                this.RaisePropertyChanged("TRIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LR_NO {
            get {
                return this.lR_NOField;
            }
            set {
                this.lR_NOField = value;
                this.RaisePropertyChanged("LR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
                this.RaisePropertyChanged("VBELN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string SHORT_PART {
            get {
                return this.sHORT_PARTField;
            }
            set {
                this.sHORT_PARTField = value;
                this.RaisePropertyChanged("SHORT_PART");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FKDAT {
            get {
                return this.fKDATField;
            }
            set {
                this.fKDATField = value;
                this.RaisePropertyChanged("FKDAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
                this.RaisePropertyChanged("WERKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string TRANS_NAME {
            get {
                return this.tRANS_NAMEField;
            }
            set {
                this.tRANS_NAMEField = value;
                this.RaisePropertyChanged("TRANS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ADD01 {
            get {
                return this.aDD01Field;
            }
            set {
                this.aDD01Field = value;
                this.RaisePropertyChanged("ADD01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
                this.RaisePropertyChanged("CITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TRIP_DIST {
            get {
                return this.tRIP_DISTField;
            }
            set {
                this.tRIP_DISTField = value;
                this.RaisePropertyChanged("TRIP_DIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string KUNNR_D {
            get {
                return this.kUNNR_DField;
            }
            set {
                this.kUNNR_DField = value;
                this.RaisePropertyChanged("KUNNR_D");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string DEALER_NAME {
            get {
                return this.dEALER_NAMEField;
            }
            set {
                this.dEALER_NAMEField = value;
                this.RaisePropertyChanged("DEALER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SHORT_NAME {
            get {
                return this.sHORT_NAMEField;
            }
            set {
                this.sHORT_NAMEField = value;
                this.RaisePropertyChanged("SHORT_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string SHORT_QTY {
            get {
                return this.sHORT_QTYField;
            }
            set {
                this.sHORT_QTYField = value;
                this.RaisePropertyChanged("SHORT_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string BILL_QTY {
            get {
                return this.bILL_QTYField;
            }
            set {
                this.bILL_QTYField = value;
                this.RaisePropertyChanged("BILL_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string CREATED_DATE {
            get {
                return this.cREATED_DATEField;
            }
            set {
                this.cREATED_DATEField = value;
                this.RaisePropertyChanged("CREATED_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string CREATED_TIME {
            get {
                return this.cREATED_TIMEField;
            }
            set {
                this.cREATED_TIMEField = value;
                this.RaisePropertyChanged("CREATED_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string UPD_DATE {
            get {
                return this.uPD_DATEField;
            }
            set {
                this.uPD_DATEField = value;
                this.RaisePropertyChanged("UPD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string UPD_TIME {
            get {
                return this.uPD_TIMEField;
            }
            set {
                this.uPD_TIMEField = value;
                this.RaisePropertyChanged("UPD_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string UPD_USER {
            get {
                return this.uPD_USERField;
            }
            set {
                this.uPD_USERField = value;
                this.RaisePropertyChanged("UPD_USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersData")]
    public partial class TransportersResponseDataZSD_LR_HDR_DTL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tRIP_NOField;
        
        private string lR_NOField;
        
        private string lOADON_DTField;
        
        private string tRANS_NAMEField;
        
        private string nAME1Field;
        
        private string cONS_NAMEField;
        
        private string dEALER_NAMEField;
        
        private string bILL_QTYField;
        
        private string vEHICLE_TYPEField;
        
        private string sGUIDField;
        
        private string tGUIDField;
        
        private string cREATED_DATEField;
        
        private string cREATED_TIMEField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string uPD_DATEField;
        
        private string uPD_TIMEField;
        
        private string uPD_USERField;
        
        private string fKSTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TRIP_NO {
            get {
                return this.tRIP_NOField;
            }
            set {
                this.tRIP_NOField = value;
                this.RaisePropertyChanged("TRIP_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LR_NO {
            get {
                return this.lR_NOField;
            }
            set {
                this.lR_NOField = value;
                this.RaisePropertyChanged("LR_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LOADON_DT {
            get {
                return this.lOADON_DTField;
            }
            set {
                this.lOADON_DTField = value;
                this.RaisePropertyChanged("LOADON_DT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANS_NAME {
            get {
                return this.tRANS_NAMEField;
            }
            set {
                this.tRANS_NAMEField = value;
                this.RaisePropertyChanged("TRANS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CONS_NAME {
            get {
                return this.cONS_NAMEField;
            }
            set {
                this.cONS_NAMEField = value;
                this.RaisePropertyChanged("CONS_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DEALER_NAME {
            get {
                return this.dEALER_NAMEField;
            }
            set {
                this.dEALER_NAMEField = value;
                this.RaisePropertyChanged("DEALER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string BILL_QTY {
            get {
                return this.bILL_QTYField;
            }
            set {
                this.bILL_QTYField = value;
                this.RaisePropertyChanged("BILL_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string VEHICLE_TYPE {
            get {
                return this.vEHICLE_TYPEField;
            }
            set {
                this.vEHICLE_TYPEField = value;
                this.RaisePropertyChanged("VEHICLE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string CREATED_DATE {
            get {
                return this.cREATED_DATEField;
            }
            set {
                this.cREATED_DATEField = value;
                this.RaisePropertyChanged("CREATED_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CREATED_TIME {
            get {
                return this.cREATED_TIMEField;
            }
            set {
                this.cREATED_TIMEField = value;
                this.RaisePropertyChanged("CREATED_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string UPD_DATE {
            get {
                return this.uPD_DATEField;
            }
            set {
                this.uPD_DATEField = value;
                this.RaisePropertyChanged("UPD_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string UPD_TIME {
            get {
                return this.uPD_TIMEField;
            }
            set {
                this.uPD_TIMEField = value;
                this.RaisePropertyChanged("UPD_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string UPD_USER {
            get {
                return this.uPD_USERField;
            }
            set {
                this.uPD_USERField = value;
                this.RaisePropertyChanged("UPD_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string FKSTO {
            get {
                return this.fKSTOField;
            }
            set {
                this.fKSTOField = value;
                this.RaisePropertyChanged("FKSTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransportersData_OUTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersData", Order=0)]
        public TrackoApi.Service.Bajaj.Data.TransportersDataRequest TransportersDataRequest;
        
        public TransportersData_OUTRequest() {
        }
        
        public TransportersData_OUTRequest(TrackoApi.Service.Bajaj.Data.TransportersDataRequest TransportersDataRequest) {
            this.TransportersDataRequest = TransportersDataRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransportersData_OUTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersData", Order=0)]
        public TrackoApi.Service.Bajaj.Data.TransportersResponseData TransportersResponseData;
        
        public TransportersData_OUTResponse() {
        }
        
        public TransportersData_OUTResponse(TrackoApi.Service.Bajaj.Data.TransportersResponseData TransportersResponseData) {
            this.TransportersResponseData = TransportersResponseData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransportersData_OUTChannel : TrackoApi.Service.Bajaj.Data.TransportersData_OUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportersData_OUTClient : System.ServiceModel.ClientBase<TrackoApi.Service.Bajaj.Data.TransportersData_OUT>, TrackoApi.Service.Bajaj.Data.TransportersData_OUT {
        
        public TransportersData_OUTClient() {
        }
        
        public TransportersData_OUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportersData_OUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportersData_OUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportersData_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrackoApi.Service.Bajaj.Data.TransportersData_OUTResponse TrackoApi.Service.Bajaj.Data.TransportersData_OUT.TransportersData_OUT(TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest request) {
            return base.Channel.TransportersData_OUT(request);
        }
        
        public TrackoApi.Service.Bajaj.Data.TransportersResponseData TransportersData_OUT(TrackoApi.Service.Bajaj.Data.TransportersDataRequest TransportersDataRequest) {
            TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest inValue = new TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest();
            inValue.TransportersDataRequest = TransportersDataRequest;
            TrackoApi.Service.Bajaj.Data.TransportersData_OUTResponse retVal = ((TrackoApi.Service.Bajaj.Data.TransportersData_OUT)(this)).TransportersData_OUT(inValue);
            return retVal.TransportersResponseData;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrackoApi.Service.Bajaj.Data.TransportersData_OUTResponse> TrackoApi.Service.Bajaj.Data.TransportersData_OUT.TransportersData_OUTAsync(TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest request) {
            return base.Channel.TransportersData_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrackoApi.Service.Bajaj.Data.TransportersData_OUTResponse> TransportersData_OUTAsync(TrackoApi.Service.Bajaj.Data.TransportersDataRequest TransportersDataRequest) {
            TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest inValue = new TrackoApi.Service.Bajaj.Data.TransportersData_OUTRequest();
            inValue.TransportersDataRequest = TransportersDataRequest;
            return ((TrackoApi.Service.Bajaj.Data.TransportersData_OUT)(this)).TransportersData_OUTAsync(inValue);
        }
    }
}
