//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackoApi.Service.Bajaj.Data.Response {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse", ConfigurationName="Bajaj.Data.Response.TransportersDataResponse_OUT")]
    public interface TransportersDataResponse_OUT {
        
        // CODEGEN: Generating message contract since the operation TransportersDataResponse_OUT is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void TransportersDataResponse_OUT(TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        System.Threading.Tasks.Task TransportersDataResponse_OUTAsync(TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransportersDataResponseRecords[] zSD_DAM_DTL_STGField;
        
        private TransportersDataResponseRecords1[] zSD_DEL_DET_STGField;
        
        private TransportersDataResponseRecords2[] zSD_DTAG_STGField;
        
        private TransportersDataResponseRecords3[] zSD_FRT_DTL_STGField;
        
        private TransportersDataResponseRecords4[] zSD_LR_DET_STGField;
        
        private TransportersDataResponseRecords5[] zSD_SRT_DTL_STGField;
        
        private TransportersDataResponseRecords6[] zSD_LR_HDR_DTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransportersDataResponseRecords[] ZSD_DAM_DTL_STG {
            get {
                return this.zSD_DAM_DTL_STGField;
            }
            set {
                this.zSD_DAM_DTL_STGField = value;
                this.RaisePropertyChanged("ZSD_DAM_DTL_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransportersDataResponseRecords1[] ZSD_DEL_DET_STG {
            get {
                return this.zSD_DEL_DET_STGField;
            }
            set {
                this.zSD_DEL_DET_STGField = value;
                this.RaisePropertyChanged("ZSD_DEL_DET_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransportersDataResponseRecords2[] ZSD_DTAG_STG {
            get {
                return this.zSD_DTAG_STGField;
            }
            set {
                this.zSD_DTAG_STGField = value;
                this.RaisePropertyChanged("ZSD_DTAG_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransportersDataResponseRecords3[] ZSD_FRT_DTL_STG {
            get {
                return this.zSD_FRT_DTL_STGField;
            }
            set {
                this.zSD_FRT_DTL_STGField = value;
                this.RaisePropertyChanged("ZSD_FRT_DTL_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransportersDataResponseRecords4[] ZSD_LR_DET_STG {
            get {
                return this.zSD_LR_DET_STGField;
            }
            set {
                this.zSD_LR_DET_STGField = value;
                this.RaisePropertyChanged("ZSD_LR_DET_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransportersDataResponseRecords5[] ZSD_SRT_DTL_STG {
            get {
                return this.zSD_SRT_DTL_STGField;
            }
            set {
                this.zSD_SRT_DTL_STGField = value;
                this.RaisePropertyChanged("ZSD_SRT_DTL_STG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Records", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TransportersDataResponseRecords6[] ZSD_LR_HDR_DTL {
            get {
                return this.zSD_LR_HDR_DTLField;
            }
            set {
                this.zSD_LR_HDR_DTLField = value;
                this.RaisePropertyChanged("ZSD_LR_HDR_DTL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponseRecords : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponseRecords1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponseRecords2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponseRecords3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponseRecords4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponseRecords5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse")]
    public partial class TransportersDataResponseRecords6 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tGUIDField;
        
        private string tRANSFER_DATEField;
        
        private string tRANSFER_TIMEField;
        
        private string tRANSFER_BATCHField;
        
        private string tRANSFER_USERField;
        
        private string sGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TGUID {
            get {
                return this.tGUIDField;
            }
            set {
                this.tGUIDField = value;
                this.RaisePropertyChanged("TGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
                this.RaisePropertyChanged("TRANSFER_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string TRANSFER_BATCH {
            get {
                return this.tRANSFER_BATCHField;
            }
            set {
                this.tRANSFER_BATCHField = value;
                this.RaisePropertyChanged("TRANSFER_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string TRANSFER_USER {
            get {
                return this.tRANSFER_USERField;
            }
            set {
                this.tRANSFER_USERField = value;
                this.RaisePropertyChanged("TRANSFER_USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string SGUID {
            get {
                return this.sGUIDField;
            }
            set {
                this.sGUIDField = value;
                this.RaisePropertyChanged("SGUID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransportersDataResponse_OUT1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bajajauto.co.in/TransAPI/TransportersDataResponse", Order=0)]
        public TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse TransportersDataResponse;
        
        public TransportersDataResponse_OUT1() {
        }
        
        public TransportersDataResponse_OUT1(TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse TransportersDataResponse) {
            this.TransportersDataResponse = TransportersDataResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransportersDataResponse_OUTChannel : TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportersDataResponse_OUTClient : System.ServiceModel.ClientBase<TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT>, TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT {
        
        public TransportersDataResponse_OUTClient() {
        }
        
        public TransportersDataResponse_OUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportersDataResponse_OUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportersDataResponse_OUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportersDataResponse_OUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT.TransportersDataResponse_OUT(TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1 request) {
            base.Channel.TransportersDataResponse_OUT(request);
        }
        
        public void TransportersDataResponse_OUT(TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse TransportersDataResponse) {
            TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1 inValue = new TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1();
            inValue.TransportersDataResponse = TransportersDataResponse;
            ((TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT)(this)).TransportersDataResponse_OUT(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT.TransportersDataResponse_OUTAsync(TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1 request) {
            return base.Channel.TransportersDataResponse_OUTAsync(request);
        }
        
        public System.Threading.Tasks.Task TransportersDataResponse_OUTAsync(TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse TransportersDataResponse) {
            TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1 inValue = new TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT1();
            inValue.TransportersDataResponse = TransportersDataResponse;
            return ((TrackoApi.Service.Bajaj.Data.Response.TransportersDataResponse_OUT)(this)).TransportersDataResponse_OUTAsync(inValue);
        }
    }
}
