// <auto-generated />
using System;
using IWLT.TrackoAPI.Subscription.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IWLT.TrackoAPI.Subscription.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.DatabaseBackupLog", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("Exception")
                        .HasMaxLength(4000);

                    b.Property<DateTime>("FinishDate");

                    b.Property<bool>("IsBackupFailed");

                    b.Property<bool>("IsPublished")
                        .HasColumnName("IsPublished");

                    b.Property<string>("LocalFilePath")
                        .HasMaxLength(500);

                    b.Property<double>("LocalFileSize");

                    b.Property<double>("RemoteFileSize");

                    b.Property<string>("RemoteServerPath")
                        .HasMaxLength(4000);

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("BackupLogs");
                });

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.EventType", b =>
                {
                    b.Property<int>("EventCode");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("SubscriberId");

                    b.HasKey("EventCode");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("SubscriberId");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.JobTrack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset?>("CreatedAt");

                    b.Property<string>("Error");

                    b.Property<string>("EventBody");

                    b.Property<int?>("EventCode");

                    b.Property<string>("EventLogId");

                    b.Property<bool>("IsProcessed");

                    b.Property<string>("JobLogId")
                        .HasMaxLength(255);

                    b.Property<DateTimeOffset?>("ProcessedTime");

                    b.Property<string>("SenderId");

                    b.Property<string>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("EventCode");

                    b.HasIndex("SenderId");

                    b.HasIndex("TenantId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.Subscriber", b =>
                {
                    b.Property<string>("Id");

                    b.Property<int?>("EventTypeEventCode");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("OriginHost");

                    b.Property<string>("Token")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("EventTypeEventCode");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Integrations");
                });

            modelBuilder.Entity("Tenant.Models.Application", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(50);

                    b.Property<int>("ApplicationType");

                    b.Property<bool>("IsActive");

                    b.Property<string>("UpdateUrl");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationName")
                        .IsUnique()
                        .HasFilter("[ApplicationName] IS NOT NULL");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Tenant.Models.TenantApplicationMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationId")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<int>("NoOfActiveUsers");

                    b.Property<string>("TenantId")
                        .IsRequired();

                    b.Property<string>("UpdateUrl");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantApplications");
                });

            modelBuilder.Entity("Tenant.Models.TenantMaster", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessCode");

                    b.Property<string>("ClientKey")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("ConnectionString")
                        .IsRequired();

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsSingleUserMode");

                    b.Property<int>("LogType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PANNo")
                        .HasMaxLength(10);

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("PostalAddress")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("RemoteBackupPath")
                        .HasMaxLength(500);

                    b.Property<string>("Secret");

                    b.Property<string>("ServerUrl");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100);

                    b.Property<string>("WebAddress")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("AccessCode")
                        .IsUnique();

                    b.HasIndex("ClientKey")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PANNo")
                        .IsUnique()
                        .HasFilter("[PANNo] IS NOT NULL");

                    b.HasIndex("ShortName")
                        .IsUnique()
                        .HasFilter("[ShortName] IS NOT NULL");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Tenant.Models.WebApiUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationKey");

                    b.Property<string>("IP");

                    b.Property<string>("RequestContent");

                    b.Property<string>("RequestHeaders");

                    b.Property<string>("RequestMethod");

                    b.Property<DateTime>("RequestTimestamp");

                    b.Property<string>("ResponseContent");

                    b.Property<string>("ResponseHeaders");

                    b.Property<int>("ResponseStatusCode");

                    b.Property<DateTime>("ResponseTimestamp");

                    b.Property<string>("TenantKey");

                    b.Property<string>("Uri");

                    b.Property<long>("UserKey");

                    b.HasKey("Id");

                    b.ToTable("ApiLog");
                });

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.DatabaseBackupLog", b =>
                {
                    b.HasOne("Tenant.Models.TenantMaster", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.EventType", b =>
                {
                    b.HasOne("IWLT.TrackoAPI.Subscription.Models.Subscriber")
                        .WithMany("SubscribedEvents")
                        .HasForeignKey("SubscriberId");
                });

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.JobTrack", b =>
                {
                    b.HasOne("IWLT.TrackoAPI.Subscription.Models.EventType", "fk_EventType")
                        .WithMany()
                        .HasForeignKey("EventCode");

                    b.HasOne("IWLT.TrackoAPI.Subscription.Models.Subscriber", "fk_Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.HasOne("Tenant.Models.TenantMaster", "fk_Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");
                });

            modelBuilder.Entity("IWLT.TrackoAPI.Subscription.Models.Subscriber", b =>
                {
                    b.HasOne("IWLT.TrackoAPI.Subscription.Models.EventType")
                        .WithMany("Subscribers")
                        .HasForeignKey("EventTypeEventCode");
                });

            modelBuilder.Entity("Tenant.Models.TenantApplicationMapping", b =>
                {
                    b.HasOne("Tenant.Models.Application", "fk_Application")
                        .WithMany("Tenants")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tenant.Models.TenantMaster", "fk_Tenant")
                        .WithMany("Applications")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
